Areas/Admin/Controllers/AdminUsersController.cs
using CoreStoreMVC.Data;
using CoreStoreMVC.Models;
using CoreStoreMVC.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreStoreMVC.Areas.Admin.Controllers
{
   [Authorize(Roles = SD.SuperAdminEndUser)]
   [Area("Admin")]
    public class AdminUsersController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AdminUsersController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _db.ApplicationUsers.ToListAsync();
            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> EditUsers(string id)
        {
            //if (id != null && id.Length > 0)
            //    id = id.Trim();

            if (id is null || id.Trim().Length is 0)
                return NotFound();


            var users = await _db.ApplicationUsers.FindAsync(id);


            if (users == null)
                return NotFound();

            return View(users);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>EditUsers(string id, ApplicationUser applicationUser)
        {
            if (applicationUser.Id != id)
                return NotFound();

            if (!ModelState.IsValid)
                return View(applicationUser);

            var user = await _db.ApplicationUsers.FindAsync(id);
            if (user is null)
                return NotFound();

            user.Name = applicationUser.Name;
            user.PhoneNumber = applicationUser.PhoneNumber;
            
            await _db.SaveChangesAsync();

            TempData["SM"] = $"Application user{applicationUser.Name} editing successful.";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id is null || id.Trim().Length is 0)
                return NotFound();
            var user = await _db.ApplicationUsers.FindAsync(id);

            if (user is null)
                return NotFound();

            return View(user);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(string id)
        {
            var user = await _db.ApplicationUsers.FindAsync(id);

            user.LockoutEnd = DateTime.Now.AddYears(1000);

            await _db.SaveChangesAsync();


            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Controllers/ProductsController.cs
using CoreStoreMVC.Data;
using CoreStoreMVC.Models;
using CoreStoreMVC.Models.ViewModel;
using CoreStoreMVC.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

// Урок 4
namespace CoreStoreMVC.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area(nameof(Admin))]
    public class ProductsController : Controller
    {
        
        // 1. Внедряем зависимость базы данных
        private readonly ApplicationDbContext _db;

        
        // V. Добавляем переменную для получения пути к корню сайта
        private readonly IWebHostEnvironment _hostingEnvironment;

        
        // 2. Добавляем свойство с атрибутом для всего контроллера
        [BindProperty]
        public ProductsViewModel ProductsVM { get; set; }

        public ProductsController(ApplicationDbContext db, IWebHostEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;

            
            // 3. Инициализируем в конструкторе свойство значениями
            ProductsVM = new ProductsViewModel()
            {
                Products = new Product(),
                ProductTypes = _db.ProductsTypes.ToList(),
                SpecialTags = _db.SpecialTags.ToList()
            };
        }

       
        // 4. Реализовать метод
        public async Task<IActionResult> Index()
        {
            // Заполняем модель данными, в том числе и из связанных таблиц
            var products = _db.Products.Include(x => x.ProductTypes).Include(x => x.SpecialTags);
            return View(await products.ToListAsync());
        }

        
        // 1. Добавляем метод Create
        // GET: Products/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View(ProductsVM);
        }

       
        // 2. Добавляем POST метод Create
        // POST: Products/Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            // I. Проверить модель на валидность
            if (!ModelState.IsValid)
                return View(ProductsVM);

            // II. Если модель валидна, добавляем информацию в сущности
            await _db.Products.AddAsync(ProductsVM.Products);
            // III. Сохраняем изменения в базе данных
            await _db.SaveChangesAsync();

            // IV. Логика сохранения картинок
            // Image begin saved
            string webRootPath = _hostingEnvironment.WebRootPath;

            // На этом месте СОЗДАТЬ папку в главном проекте Utility

            // Получаем файлы из формы
            var files = HttpContext.Request.Form.Files;

            // Получаем товары из базы данных
            var productsFromDb = await _db.Products.FindAsync(ProductsVM.Products.Id);

            // Проверяем, получены ли какие-то файлы
            if (files.Count != 0)
            {
                // Image has been uploaded
                // I. Комбинируем путь к папке сохранения
                var uploadPath = Path.Combine(webRootPath, SD.ImageFolder);

                // II. Получаем расширение полученного файла
                var extension = Path.GetExtension(files[0].FileName);

                // III. Сохраняем картинки
                using (var fileStream = new FileStream(Path.Combine(uploadPath, ProductsVM.Products.Id + extension), FileMode.Create))
                {
                    await files[0].CopyToAsync(fileStream);
                }

                // IV. Записываем в базу путь к сохранённой картинке
                productsFromDb.Image = $"\\{SD.ImageFolder}\\{ProductsVM.Products.Id}{extension}";
            }
            else
            {
                // V. На этом этапе добавляем в папку ProductImage default_product.png
                // Формируем путь к изображению по умолчанию
                var uploadPath = Path.Combine(webRootPath, SD.ImageFolder + @"\" + SD.DefaultProductImage);

                // Копируем картинку в папку изображения продукта
                System.IO.File.Copy(uploadPath, webRootPath + @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".png");
                // Сохраняем путь к картинке в модель
                productsFromDb.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".png";
            }

            // VI. Сохраняем все изменения в базе
            await _db.SaveChangesAsync();

            // Добавляем сообщение о удачном добавлении
            TempData["SM"] = $"Product {ProductsVM.Products.Name} adding successful!";

            // Переадресовываем пользователя на страницу Index
            return RedirectToAction(nameof(Index));
        }

        
        // GET: Products/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            // 1. Проверяем полученный ID на null
            if (id == null)
                return NotFound();

            // 2. Заполняем модель представления данными
            // У нас есть 3 варианта, как завершить запрос: FirstOrDefault() , SingleOrDefault() , FindAsync()
            // В большинстве скаффолдингового кода FindAsync может использоваться вместо FirstOrDefaultAsync.
            // SingleOrDefaultAsync извлекает больше данных и выполняет ненужную работу. выдает исключение, если существует более одного объекта, который соответствует части фильтра.
            // FirstOrDefaultAsync не выбрасывает, если существует более одного объекта, который соответствует части фильтра.
            ProductsVM.Products = await _db.Products
                                           .Include(x => x.ProductTypes)
                                           .Include(x => x.SpecialTags)
                                           .FirstOrDefaultAsync(x => x.Id == id);

            // 3. Проверяем, найдены ли данные
            if (ProductsVM.Products is null)
                return NotFound();

            // 4. Если модель найдена, возвращаем представление с моделью
            return View(ProductsVM);
        }

        
        // POST: Products/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            // 1. Проверить модель на валидность
            if (!ModelState.IsValid)
                return View(ProductsVM);

            // 2. Создаём необходимые переменные для путей картинки (webRootPath и file)
            string webRootPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            // 3. Получить и сохранить в отдельную переменную редактируемый товар из базы данных (это надо для обработки изображения)
            var productFromDb = _db.Products.FirstOrDefault(x => x.Id == ProductsVM.Products.Id);

            // 4. Проверяем, получены ли файлы из формы и не null ли переменная files
            if (files.Count > 0 && files[0] != null)
            {
                // 4.1 Если проверка успешно пройдена, то создаём путь к папке с изображениями
                var uploads = Path.Combine(webRootPath, SD.ImageFolder);

                // 4.2 Получаем новое расширение файла
                var extension_new = Path.GetExtension(files[0].FileName);

                // 4.3 Получаем старое расширение файла (из переменной productFromDb)
                var extension_old = Path.GetExtension(productFromDb.Image);

                // 4.4 Проверяем, имеется ли уже в наличии файл (метод System.IO.File.Exists(Path.Combine(путь_загрузки, ID_продукта + старое_расширение_файла)))
                if (System.IO.File.Exists(Path.Combine(uploads, ProductsVM.Products.Id + extension_old)))
                    // 4.4.1 Если файл имеется, то удалить его
                    System.IO.File.Delete(Path.Combine(uploads, ProductsVM.Products.Id + extension_old));

                // 4.5 После чего - копируем новый
                using (var fileStream = new FileStream(Path.Combine(uploads, ProductsVM.Products.Id + extension_new), FileMode.Create))
                {
                    await files[0].CopyToAsync(fileStream);
                }

                // 4.6 Сохраняем путь в модель представления
                ProductsVM.Products.Image = $"\\{SD.ImageFolder}\\{ProductsVM.Products.Id}{extension_new}";
            }

            // 5. Проверяем, если путь к картинке в модели не равен NULL
            if (ProductsVM.Products.Image != null)
                // 5.1 Сохраняем путь картинки в модели, полученной из базы данных (productFromDb)
                productFromDb.Image = ProductsVM.Products.Image;

            // 6. Обновляем все свойства модели productFromDb на полученные из ProductsVM
            productFromDb.Name = ProductsVM.Products.Name;
            productFromDb.Price = ProductsVM.Products.Price;
            productFromDb.Available = ProductsVM.Products.Available;
            productFromDb.ProductTypeId = ProductsVM.Products.ProductTypeId;
            productFromDb.SpecialTagId = ProductsVM.Products.SpecialTagId;
            productFromDb.ShadeColor = ProductsVM.Products.ShadeColor;

            // 7. Сохранить все изменения в базе данных
            await _db.SaveChangesAsync();

            // 8. Добавить сообщение об успешном обновлении
            TempData["SM"] = $"Product {ProductsVM.Products.Name} update successful!";

            // 9. Переадресовать пользователя на страницу Index
            return RedirectToAction(nameof(Index));
        }

        
        // GET: Products/Details
        public async Task<IActionResult> Details(int? id)
        {
            // 1. Проверяем полученный ID на null
            if (id == null)
                return NotFound();

            // 2. Заполняем модель представления данными
            ProductsVM.Products = await _db.Products

Areas/Admin/Controllers/SpecialTagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreStoreMVC.Data;
using CoreStoreMVC.Models;
using CoreStoreMVC.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoreStoreMVC.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area(nameof(Admin))]
    public class SpecialTagsController : Controller
    {
        // Создаём переменную только для чтения, чтобы использовать базу данных
        private readonly ApplicationDbContext _db;
        // Внедряем зависимость базы данных через конструктор класса
        public SpecialTagsController(ApplicationDbContext db)
        {
            // Предаём все данные в приватную переменную
            _db = db;
        }
        // GET метод представления Index
        public IActionResult Index()
        {
            
            return View(_db.SpecialTags.ToList());
        }

        // GET метод создания типов продуктов
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST метод создания типов продуктов
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTag specialTag)
        {
            // 1. Проверяем модель на валидность
            if (ModelState.IsValid)
            {
                // 1.1 Если модель валидная, то добавляем значение модели в сущности Entity Framework
                _db.Add(specialTag);

                // 1.2 Сохраняем все изменения в базе данных асинхронно
                await _db.SaveChangesAsync();

                // 1.4 Добавляем сообщение о успешном добавлении типа в TempData
                TempData["SM"] = $"Special tag: {specialTag.Name} added successful!";

                // 1.3 Переадресовываем на страницу вывода всех типов продуктов
                return RedirectToAction(nameof(Index));
            }

            // 2. Если модель не валидная, возвращаем текущее представление с моделью для исправления ошибок
            return View(specialTag);
        }

        
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var specialTag = await _db.SpecialTags.FindAsync(id);
            if (specialTag == null)
                return NotFound();

            return View(specialTag);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SpecialTag specialTag)
        {
            if (id != specialTag.Id)
                return NotFound();

            if (!ModelState.IsValid)
                return View(specialTag);

            _db.Update(specialTag);
            await _db.SaveChangesAsync();

            TempData["SM"] = $"Special tag {specialTag.Name} editing successful.";

            return RedirectToAction(nameof(Index));
        }

        
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var specialTag = await _db.SpecialTags.FindAsync(id);
            if (specialTag == null)
                return NotFound();

            return View(specialTag);
        }

        
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var specialTag = await _db.SpecialTags.FindAsync(id);

            if (specialTag == null)
                return NotFound();

            return View(specialTag);
        }
        
        // Указываем официальное имя метода через аннотацию
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Получаем тип продукта из базы и записываем её в переменную
            var specialTag = await _db.SpecialTags.FindAsync(id);

            // Проверяем, найден ли тип продукта или получен NULL
            if (specialTag != null)
            {
                // Удаляем через сущности Entity
                _db.SpecialTags.Remove(specialTag);

                // Сохраняем изменения
                await _db.SaveChangesAsync();

                // Добавляем сообщение о успешном удалении типа продукта
                TempData["SM"] = $"Special tag {specialTag.Name} deleting successful.";
            }
            else
                TempData["SM"] = $"Special tag {specialTag.Name} deleting FAILED.";
            
            // Переадресовываем на страницу Index
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_AppointmentCustomerDetails.cshtml
@*Урок 12*@
@model CoreStoreMVC.Models.Appointment

<h4 class="text-success">Appointment Details</h4>

<div class="container border" style="background-color: aliceblue">
    <div class="col-12 pt-3">
        <div class="row">
            <div class="col-sm-2">
                Full Name:
            </div>
            <div class="col-sm-3">
                <input asp-for="@Model.CustomerName" readonly class="form-control" />
            </div>

            <div class="col-sm-2 offset-2">
                Email:
            </div>
            <div class="col-sm-3">
                <input asp-for="@Model.CustomerEmail" readonly class="form-control" />
            </div>
        </div>
    </div>
    <div class="col-12 mt-1 pb-3">
        <div class="row">
            <div class="col-sm-2">
                Phone Number::
            </div>
            <div class="col-sm-3">
                <input asp-for="@Model.CustomerPhoneNumber" readonly class="form-control" />
            </div>

            <div class="col-sm-2 offset-2">
                Appointment Date:
            </div>
            <div class="col-sm-3">
                <input readonly class="form-control" value="@Model.AppointmentDay.ToString("dd.MM.yyyy HH:mm")" />
            </div>
        </div>
    </div>
</div>

Views/Shared/_AppointmentProductDetails.cshtml
@*Урок 12*@
@model List<CoreStoreMVC.Models.Product>

@if (Model.Count > 0)
{
    <table class="table table-striped" width="100%">
        <thead class="table-info text-center">
            <tr>
                <th style="width: 20%"></th>
                <th>
                    <label asp-for="@Model.FirstOrDefault().Name"></label>
                </th>
                <th>
                    <label asp-for="@Model.FirstOrDefault().Price"></label>
                </th>
                <th>
                    <label asp-for="@Model.FirstOrDefault().ShadeColor"></label>
                </th>
                <th>
                    <label asp-for="@Model.FirstOrDefault().ProductTypes.Name"></label>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="p-5 text-center">
                    <td>
                        <a asp-area="Customer" asp-controller="Home" asp-action="Details" asp-route-id="@item.Id">
                            <img src="@item.Image" width="100%" style="margin: auto; display:block; border-radius: 5px; border: 1px solid #bbb9b9;" />
                        </a>
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(x => item.Name)
                    </td>
                    <td class="align-middle">
                        @String.Format("{0:c}", item.Price)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(x => item.ShadeColor)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(x => item.ProductTypes.Name)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-danger text-center">No items added to the shopping cart...</div>
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using CoreStoreMVC.Extensions
@using CoreStoreMVC.Utility

@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreStoreMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Core Store MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.SuperAdminEndUser)) { 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a>
                            </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Special Tags</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">Admin users</a>
                        </li>
                        }
                        @if (User.IsInRole(SD.AdminEndUser)) { 
                        @if (HttpContextAccessor.HttpContext.Session.Get<List<int>>("sShoppingCart") != null)
                        {
                            <li>
                                <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i>
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<int>>("sShoppingCart").Count;
                                    }
                                    (@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color: white">
                                <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i>

                                    (0)
                                </a>
                            </li>
                        }
                     }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Core Store MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/e4fa5c8403.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_TableButtonPartial.cshtml
@*Шаг 1: Назначаем модель*@
@model int
@using System.Web

@*Шаг 2: Создаём разметку для кнопок*@
<td style="width: 150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary" href="@HttpUtility.UrlDecode(Url.Action($"Edit/{Model}"))">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-success" href="@HttpUtility.UrlDecode(Url.Action($"Details/{Model}"))">
            <i class="fas fa-list-alt"></i>
        </a>
        <a class="btn btn-danger" href="@HttpUtility.UrlDecode(Url.Action($"Delete/{Model}"))">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>